### ISSUE TITLE
Gracefully shutdown the agent

### ISSUE THREAD

**Issue by jigneshjain25** [google/inverting-proxy#100]
- Add a new optional (via flag) feature for enabling gracefully shutting down the agent
- We should stop pulling new requests and drain the already pulled/being processed ones during the graceful shutdown time window. Basically the agent should act in a "lame duck" mode when received a shutdown signal from the OS.

**Comment by ojarjur** [comment]
@jigneshjain25 can you confirm that #101 fixed this and this issue can be closed now?

**Comment by jigneshjain25** [comment]
@ojarjur yes.
