### ISSUE TITLE
Cache cookies agent-side.

### ISSUE THREAD

**Issue by JDarDagran** [google/inverting-proxy#103]
Hello,

we have a need to run 3rd party software in Vertex AI Workbench that uses cookies. It turns out that Google managed proxies listed [here](https://storage.googleapis.com/dl-platform-public-configs/proxy-agent-config.json) are cutting `Set-Cookie` headers in some way. On the other hand I checked that `inverting-proxy` image is used as `proxy-agent` on the VM provisioned by Vertex.

I got two questions to the issue:
1. are there any known solutions/workaround that would allow us to pass cookies through proxy?
2. if no, what approach would you recommend? My current solution is following:

* add another `lru.Cache` that stores cookies per URL & another pointer. In my case I'm using parametrized path in headers like `DATALAB_TUNNEL_TOKEN` which is unique per user.
* restore cache in similar way `sessionResponseWriter` does

All above are derived only from looking at `attempt-register-vm-on-proxy.sh` script, if anything is not true please correct me.

Would be happy to contribute with a bit of guidance!

**Comment by ojarjur** [comment]
Yes, the agent supports tracking cookies on the agent side. This is controlled by the `session-cookie-name` flag, or the `SESSION_COOKIE_NAME` environment variable, if you are using the provided agent Docker image.

That being said, you would need to file a feature request with the Vertex AI Workbench product to support this, as you need to have a cookie that you can use as the session cookie that is not filtered out by the proxy.
