### ISSUE TITLE
Fix golint errors

### ISSUE THREAD

**Issue by ojarjur** [google/inverting-proxy#2]
I apparently forgot to lint this code before committing it.

We need to go through and fix all of the issues reported by running `golint ./...`

**Comment by whuang8** [comment]
Thoughts on running the linter during CI? I can work on adding it to the travis config if this is wanted :)

**Comment by ojarjur** [comment]
@whuang8 Adding a lint check to our travis config would be very much appreciated. Thanks for your help here!
