### ISSUE TITLE
Binary websocket messages come as text

### ISSUE THREAD

**Issue by vsavenkov** [google/inverting-proxy#47]
I ran into a problem trying to get certain IPywidgets work under the proxy on Google Cloud. For instance, the following notebook renders fine on a custom VM with nginx proxy on GCE, but not on an AI Platform notebook with the pre-configured  inverting proxy: https://github.com/seidlr/voila-interactive-football-pitch/blob/master/Interactive-Football-Pitch.ipynb. 

With the inverting proxy, binary WebSocket or poll messages are treated as ordinary text messages by the browser, resulting in the JSON parsing error, with or without Shim.

**Comment by ojarjur** [comment]
This can be reproduced with a notebook that contains a single cell with the following code:

```py
import ipywidgets

ipywidgets.Image(value='', format='png')
```
