### ISSUE TITLE
Is Google App Engine required?

### ISSUE THREAD

**Issue by functicons** [google/inverting-proxy#53]
The Usage section states that GAE is a prerequisite, but IIUC it is just an example usage with GAE. It would be nice if we could be more explicit, and provide instructions on running the inverting proxy in non-GAE environments.

**Comment by ojarjur** [comment]
This is a good question.

The first version was App-Engine only.

There is now a stand-alone version [here](https://github.com/google/inverting-proxy/blob/master/server/server.go), but it is very rudimentary and does not have most of the features of the AppEngine version.

In particular, it is missing any form of auth and has no mechanism for scaling beyond a single server.

Those are things that *could* be added to the stand-alone server, but until they are added the stand-alone server is mostly just suitable for testing.

**Comment by functicons** [comment]
Thanks for the clarification!
