### ISSUE TITLE
`make deploy` fails to properly deploy working app

### ISSUE THREAD

**Issue by ravwojdyla** [google/inverting-proxy#93]
👋 I'm very excited about inverting-proxy, thanks for open sourcing it, I would appreciate some deployment guidance, I had some trouble deploying to GAE mentioned in #91, even tho fixing that allowed to deploy to GAE (using the `make deploy`), the apps are not actually properly deployed, in the logs I can see:

> /bin/sh: 1: exec: main: Permission denied

I unfortunately don't have a lot of experience with GAE or go, and it's a bit hard to debug GAE without access to the VMs. After some reading/trial/error I could workaround the issue by adding a `main` akin to https://cloud.google.com/appengine/docs/standard/go/reference/services/bundled/latest#google_golang_org_appengine_v2_Main

Any help would be greatly appreciated.

---

Env:

```bash
~ gcloud version
Google Cloud SDK 344.0.0
alpha 2021.06.04
app-engine-go 1.9.72
app-engine-python 1.9.98
beta 2021.06.04
bq 2.0.69
core 2021.06.04
gsutil 4.62

~ go version
go version go1.13.9 linux/amd64
```

**Comment by ravwojdyla** [comment]
This seems to fixes with deployment: 
 * #91 
 * `app_engine_apis: true` in the yaml specs (otherwise datastore requests fail)
 * change `gcloud app deploy` to `gcloud beta app deploy` in Makefile
 * updated appengine SDK to appengine/v2 (might not be actually needed)

**Comment by ravwojdyla** [comment]
Please let me know if there is anything missing, and whether you would like a PR with those changes.

**Comment by ojarjur** [comment]
Thanks for catching this and digging into it.

Sorry for the late response; I had my GitHub notification settings misconfigured for a long time, and so didn't see this.

All of those changes sound reasonable.

**Comment by ojarjur** [comment]
I've found that I had to do more extensive restructuring to get the app working in the new `go116` runtime, but did eventually get it to work.

The PR for those changes is [here](https://github.com/google/inverting-proxy/pull/110)

**Comment by ojarjur** [comment]
Fixed now. Thanks for reporting this, and sorry for the delay getting it updated.
