### ISSUE TITLE
Example of websocket setup (e.g. Jupyter Lab)?

### ISSUE THREAD

**Issue by ravwojdyla** [google/inverting-proxy#95]
👋 please correct me if I'm wrong, the "AI Notebooks" use inverting-proxy to expose Jupyter Lab which uses websockets, I'm curious if you have an example of config/setup for a backend that uses websockets, e.g. Jupyter Lab? Or could you please shed some more light on how "AI Notebooks" use inverting-proxy please?

Btw I have see the comment in README:

> Currently, the App Engine version of the inverting proxy only supports HTTP requests. In particular, websockets are not supported, so you have to use an adapter like socket.io if you want to use the inverting proxy with a service that requires websockets.

**Comment by ojarjur** [comment]
The limitations on using websockets is limited to the app engine version of the proxy. Other versions do not have that restriction.

AI Notebooks does not use the App Engine version of the proxy.

However, if you do want to use the App Engine version, websockets can still work by enabling the websocket-shimming feature of the proxy agent.

That will cause served HTML pages to have javascript code injected into them that replaces websocket connections with HTTP requests.

The flags to enable that are [here](https://github.com/google/inverting-proxy/blob/4af0bd5e984ef90b8fe26dda9e0091f2fdc2f3f5/agent/agent.go#L70). Specifically, you want to add the `--shim-websockets` flag, and define a value for the `--shim-path` flag (e.g. `--shim-path=/websocket-shim`).
